In [1]:
import pandas as pd
import time

In [2]:
data = pd.read_csv("./fake_data/data.csv", header=None)
data.head(5)

,0,1,2,3,4,5,6,7,8
0,津A41519,2020-02-07 04:59:06.657639,2020-02-07 05:15:06.657639,2020-02-07 05:11:54.657639,23,1581023514,31,23306d2ded78abcf97e42651ff44bf4c,456.0
1,津A13800,2020-02-07 02:27:50.657639,2020-02-07 02:45:50.657639,2020-02-07 02:42:14.657639,20,1581014534,33,53855ba7941dcad039bd09518696f8fe,365.0
2,津A27581,2020-02-07 16:17:28.657639,2020-02-07 16:27:28.657639,2020-02-07 16:25:28.657639,54,1581063928,34,915e1f65e3d466d1b2ccd500bae6bbf0,426.0
3,津A16997,2020-02-07 03:24:29.657639,2020-02-07 03:52:29.657639,2020-02-07 03:46:53.657639,174,1581018413,30,8a7bd5cc47f57d6b82ead404c6aec7a1,459.0
4,津A49948,2020-02-07 02:48:51.657639,2020-02-07 02:57:51.657639,2020-02-07 02:56:03.657639,169,1581015363,33,7b8084e1d720f0432dd3cc7b54260718,290.0

In [3]:
data.columns = ["车牌", "到站时间", "离站时间", "支付时间", "加油站编号", "订单编号", "支付方式","支付id(三方ID)", "金额"]

In [4]:
data.head(5)

,车牌,到站时间,离站时间,支付时间,加油站编号,订单编号,支付方式,支付id(三方ID),金额
0,津A41519,2020-02-07 04:59:06.657639,2020-02-07 05:15:06.657639,2020-02-07 05:11:54.657639,23,1581023514,31,23306d2ded78abcf97e42651ff44bf4c,456.0
1,津A13800,2020-02-07 02:27:50.657639,2020-02-07 02:45:50.657639,2020-02-07 02:42:14.657639,20,1581014534,33,53855ba7941dcad039bd09518696f8fe,365.0
2,津A27581,2020-02-07 16:17:28.657639,2020-02-07 16:27:28.657639,2020-02-07 16:25:28.657639,54,1581063928,34,915e1f65e3d466d1b2ccd500bae6bbf0,426.0
3,津A16997,2020-02-07 03:24:29.657639,2020-02-07 03:52:29.657639,2020-02-07 03:46:53.657639,174,1581018413,30,8a7bd5cc47f57d6b82ead404c6aec7a1,459.0
4,津A49948,2020-02-07 02:48:51.657639,2020-02-07 02:57:51.657639,2020-02-07 02:56:03.657639,169,1581015363,33,7b8084e1d720f0432dd3cc7b54260718,290.0

In [5]:
def change_to_timestamp(date):
    timeArray = time.strptime(str(date), "%Y-%m-%d %H:%M:%S.%f")
    timestamp = time.mktime(timeArray)
    return timestamp

In [6]:
cols = ["到站时间", "离站时间", "支付时间"]
for col in cols:
    data[col] = data[col].apply(change_to_timestamp)
data

,车牌,到站时间,离站时间,支付时间,加油站编号,订单编号,支付方式,支付id(三方ID),金额
0,津A41519,1.581023e+09,1.581024e+09,1.581024e+09,23,1581023514,31,23306d2ded78abcf97e42651ff44bf4c,456.0
1,津A13800,1.581014e+09,1.581015e+09,1.581015e+09,20,1581014534,33,53855ba7941dcad039bd09518696f8fe,365.0
2,津A27581,1.581063e+09,1.581064e+09,1.581064e+09,54,1581063928,34,915e1f65e3d466d1b2ccd500bae6bbf0,426.0
3,津A16997,1.581017e+09,1.581019e+09,1.581018e+09,174,1581018413,30,8a7bd5cc47f57d6b82ead404c6aec7a1,459.0
4,津A49948,1.581015e+09,1.581015e+09,1.581015e+09,169,1581015363,33,7b8084e1d720f0432dd3cc7b54260718,290.0
...,...,...,...,...,...,...,...,...,...
595,津A22213,1.575909e+09,1.575909e+09,1.575909e+09,94,1575909005,33,3b581da7088775aee511ff0a90010d57,490.0
596,津A40281,1.575917e+09,1.575918e+09,1.575918e+09,164,1575917841,33,4cf46692885a1663fc860d672677ca80,279.0
597,津A10343,1.575956e+09,1.575957e+09,1.575957e+09,79,1575957127,30,a14a539baacce03c81bbc5f15a186557,312.0
598,津A45215,1.575974e+09,1.575975e+09,1.575975e+09,168,1575974937,34,fd40fd108cfee230409b50249480e5db,387.0
599,津A13099,1.575993e+09,1.575995e+09,1.575995e+09,101,1575994579,33,11991ef84d0ca5232340ddff02a0efb8,456.0

In [7]:
data.to_csv("data.csv", index=False, header=True, sep=",", encoding="utf-8_sig")

In [8]:
def get_jiayou_data(data):
    jiayou_data = pd.DataFrame(data, columns=["车牌", "到站时间", "离站时间"]) 
    return jiayou_data
jiayou_data = get_jiayou_data(data)
jiayou_data.to_csv("jiayou_data.csv", index=False, header=True, sep=",", encoding="utf-8_sig")
jiayou_data.head(5)

        车牌          到站时间          离站时间
0  津A41519  1.581023e+09  1.581024e+09
1  津A13800  1.581014e+09  1.581015e+09
2  津A27581  1.581063e+09  1.581064e+09
3  津A16997  1.581017e+09  1.581019e+09
4  津A49948  1.581015e+09  1.581015e+09

In [9]:
def get_pay_data(data):
    pay_data = pd.DataFrame(data, columns=["支付时间", "加油站编号", "订单编号", "支付方式","支付id(三方ID)", "金额"]) 
    return data
pay_data = get_pay_data(data)
pay_data.to_csv("pay_data.csv", index=False, header=True, sep=",", encoding="utf-8_sig")
pay_data.head(5)

,车牌,到站时间,离站时间,支付时间,加油站编号,订单编号,支付方式,支付id(三方ID),金额
0,津A41519,1.581023e+09,1.581024e+09,1.581024e+09,23,1581023514,31,23306d2ded78abcf97e42651ff44bf4c,456.0
1,津A13800,1.581014e+09,1.581015e+09,1.581015e+09,20,1581014534,33,53855ba7941dcad039bd09518696f8fe,365.0
2,津A27581,1.581063e+09,1.581064e+09,1.581064e+09,54,1581063928,34,915e1f65e3d466d1b2ccd500bae6bbf0,426.0
3,津A16997,1.581017e+09,1.581019e+09,1.581018e+09,174,1581018413,30,8a7bd5cc47f57d6b82ead404c6aec7a1,459.0
4,津A49948,1.581015e+09,1.581015e+09,1.581015e+09,169,1581015363,33,7b8084e1d720f0432dd3cc7b54260718,290.0

In [10]:
pay_data.shape

(600, 9)

In [11]:
len(set(jiayou_data["车牌"].values))

598

In [12]:
len(set(pay_data["支付id(三方ID)"].values))

598

In [13]:
chepai_id = set(jiayou_data["车牌"].values)
pay_id = set(pay_data["支付id(三方ID)"].values)
gas_station = set(data["加油站编号"].values)

In [14]:
def get_chepai_dict(chepai_id, jiayou_data):
    chepai_dict = dict()
    for chepai in chepai_id:
        data_tmp = jiayou_data[jiayou_data["车牌"] == chepai]
        arrive_time = data_tmp["到站时间"].values
        leave_time = data_tmp["离站时间"].values
        tmp_dict = {"arrive_time": arrive_time, "leave_time": leave_time}
        chepai_dict[chepai] = tmp_dict
    return chepai_dict
chepai_dict = get_chepai_dict(chepai_id, jiayou_data)

In [15]:
def get_pay_dict(pay_data, pay_id):
    pay_dict = dict()
    for id in pay_id:
        data_tmp = pay_data[pay_data["支付id(三方ID)"] == id]
        pay_time = data_tmp["支付时间"].values
        tmp_dict = {"pay_time": pay_time}
        pay_dict[id] = tmp_dict
    return pay_dict
pay_dict = get_pay_dict(pay_data, pay_id)

In [16]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
def consine_similiar(s1, s2):
    s1 = np.array([s1])
    s2 = np.array([s2])
    return cosine_similarity(s1, s2)[0][0]

In [20]:
def get_rst(chepai_dict, pay_dict):
    rst = {"车牌": [], "支付id编号": [], "相似度": []}
    for chepai in chepai_dict:
        cosine_similar = -1.0
        arrive_time = chepai_dict[chepai]["arrive_time"]
        leave_time = chepai_dict[chepai]["leave_time"]
        final_chepai = chepai
        final_id = 0
        final_similar = 0.0
        for id in pay_dict:
            pay_time = pay_dict[id]["pay_time"]
            if len(arrive_time) == len(pay_time) and len(leave_time) == len(pay_time):
                time = (arrive_time + leave_time) / 2.0
                #similar = np.sqrt(np.sum(np.square(time-pay_time))) #欧式距离
                similar = np.linalg.norm(time-pay_time, ord = 1) #曼哈顿距离
                if similar > cosine_similar:
                    cosine_similar = similar
                    final_chepai = chepai
                    final_id = id
                    final_similar = similar
        rst["车牌"].append(final_chepai)
        rst["支付id编号"].append(final_id)
        rst["相似度"].append(final_similar)
    return rst

In [21]:
result = get_rst(chepai_dict, pay_dict)

In [22]:
rst_data = pd.DataFrame.from_dict(result)
rst_data

          车牌                            支付id编号        相似度
0    津A29582  4cf46692885a1663fc860d672677ca80  4355425.0
1    津A38941  10f9a8b18f115990d9fbb0826435e284  3533754.0
2    津A20436  4cf46692885a1663fc860d672677ca80  4431317.0
3    津A16673  10f9a8b18f115990d9fbb0826435e284  3092570.0
4    津A23227  4cf46692885a1663fc860d672677ca80  4627537.0
..       ...                               ...        ...
593  津A27278  10f9a8b18f115990d9fbb0826435e284  3406487.0
594  津A13800  4cf46692885a1663fc860d672677ca80  5096369.0
595  津A11923  10f9a8b18f115990d9fbb0826435e284  4029032.0
596  津A14470  10f9a8b18f115990d9fbb0826435e284  4997658.0
597  津A26690  10f9a8b18f115990d9fbb0826435e284  3675329.0

[598 rows x 3 columns]

In [23]:
for station in gas_station:
    temp_data = data[data["加油站编号"] == station]
    chepai_id = set(temp_data["车牌"].values)
    for id in chepai_id:
        if len(data[data["车牌"] == id]) > 1:
            print(id)

津A21321
津A22213
津A21321
津A22213

In [24]:
def validate_accuracy(data, rst_data):
    correct = 0
    for i in range(len(rst_data)):
        tmp = rst_data.loc[i]
        chepai = tmp[0]
        pay_id = tmp[1]
        real_pay_id = data[data["车牌"] == chepai]["支付id(三方ID)"].values[0]
        if real_pay_id == pay_id:
            print(chepai)
            correct += 1
    print(correct)
    return correct / len(rst_data)

In [27]:
def run(data):
    result = {"车牌": [], "支付id编号": [], "相似度": []}
    for station in gas_station:
        temp_data = data[data["加油站编号"] == station]
        pay_data = get_pay_data(temp_data)
        jiayou_data = get_jiayou_data(temp_data)
        chepai_id = set(jiayou_data["车牌"].values)
        pay_id = set(pay_data["支付id(三方ID)"].values)
        chepai_dict = get_chepai_dict(chepai_id, jiayou_data)
        pay_dict = get_pay_dict(pay_data, pay_id)
        rst = get_rst(chepai_dict, pay_dict)
        result["车牌"] = result["车牌"] + rst["车牌"]
        result["支付id编号"] = result["支付id编号"] + rst["支付id编号"]
        result["相似度"] = result["相似度"] + rst["相似度"]
    return result

In [28]:
result = run(data)

In [29]:
accuracy = validate_accuracy(data, rst_data)

0

In [30]:
accuracy

0.0

In [ ]:
chepai_list = []
for station in gas_station:
    temp_data = data[data["加油站编号"] == station]
    chepai_id = set(temp_data["车牌"].values)
    for id in chepai_id:
        if len(temp_data[temp_data["车牌"] == id]) > 1:
            chepai_list.append(id)
chepai_list

In [ ]:
cnt = 0
for chepai in chepai_list:
    real_pay_id = data[data["车牌"] == chepai]["支付id(三方ID)"].values[0]
    guanlian_data = rst_data[rst_data["车牌"] == chepai]
    for i in range(len(guanlian_data.values)):
        guanlian_pay_id = temp.values[i][1]
        print(guanlian_pay_id)
        if real_pay_id == guanlian_pay_id:
            cnt += 1

In [ ]:
cnt

In [ ]:
accuracy = cnt / len(chepai_list)